import { screens } from "./screen";

export const themePreset = {
  screens,
  colors: {
    primary: {
      50: "var(--cc-color_primary_50)",
      75: "var(--cc-color_primary_75)",
      100: "var(--cc-color_primary_100)",
      200: "var(--cc-color_primary_200)",
      300: "var(--cc-color_primary_300)",
      400: "var(--cc-color_primary_400)",
      500: "var(--cc-color_primary_500)",
      600: "var(--cc-color_primary_600)",
      700: "var(--cc-color_primary_700)",
      800: "var(--cc-color_primary_800)",
      900: "var(--cc-color_primary_900)",
    },
    secondary: {
      50: "var(--cc-color_secondary_50)",
      75: "var(--cc-color_secondary_75)",
      100: "var(--cc-color_secondary_100)",
      200: "var(--cc-color_secondary_200)",
      300: "var(--cc-color_secondary_300)",
      400: "var(--cc-color_secondary_400)",
      500: "var(--cc-color_secondary_500)",
      600: "var(--cc-color_secondary_600)",
      700: "var(--cc-color_secondary_700)",
      800: "var(--cc-color_secondary_800)",
      900: "var(--cc-color_secondary_900)",
    },
    success: {
      50: "var(--cc-color_success_50)",
      75: "var(--cc-color_success_75)",
      100: "var(--cc-color_success_100)",
      200: "var(--cc-color_success_200)",
      300: "var(--cc-color_success_300)",
      400: "var(--cc-color_success_400)",
      500: "var(--cc-color_success_500)",
      600: "var(--cc-color_success_600)",
      700: "var(--cc-color_success_700)",
      800: "var(--cc-color_success_800)",
      900: "var(--cc-color_success_900)",
    },
    warning: {
      50: "var(--cc-color_warning_50)",
      75: "var(--cc-color_warning_75)",
      100: "var(--cc-color_warning_100)",
      200: "var(--cc-color_warning_200)",
      300: "var(--cc-color_warning_300)",
      400: "var(--cc-color_warning_400)",
      500: "var(--cc-color_warning_500)",
      600: "var(--cc-color_warning_600)",
      700: "var(--cc-color_warning_700)",
      800: "var(--cc-color_warning_800)",
      900: "var(--cc-color_warning_900)",
    },
    error: {
      50: "var(--cc-color_error_50)",
      75: "var(--cc-color_error_75)",
      100: "var(--cc-color_error_100)",
      200: "var(--cc-color_error_200)",
      300: "var(--cc-color_error_300)",
      400: "var(--cc-color_error_400)",
      500: "var(--cc-color_error_500)",
      600: "var(--cc-color_error_600)",
      700: "var(--cc-color_error_700)",
      800: "var(--cc-color_error_800)",
      900: "var(--cc-color_error_900)",
    },

    neutral: {
      50: "var(--cc-color_neutral_50)",
      75: "var(--cc-color_neutral_75)",
      100: "var(--cc-color_neutral_100)",
      200: "var(--cc-color_neutral_200)",
      300: "var(--cc-color_neutral_300)",
      400: "var(--cc-color_neutral_400)",
      500: "var(--cc-color_neutral_500)",
      600: "var(--cc-color_neutral_600)",
      700: "var(--cc-color_neutral_700)",
      800: "var(--cc-color_neutral_800)",
      900: "var(--cc-color_neutral_900)",
    },
    brown: {
      50: "var(--cc-color_brown_50)",
      75: "var(--cc-color_brown_75)",
      100: "var(--cc-color_brown_100)",
      200: "var(--cc-color_brown_200)",
      300: "var(--cc-color_brown_300)",
      400: "var(--cc-color_brown_400)",
      500: "var(--cc-color_brown_500)",
      600: "var(--cc-color_brown_600)",
      700: "var(--cc-color_brown_700)",
      800: "var(--cc-color_brown_800)",
      900: "var(--cc-color_brown_900)",
    },
    white: "var(--cc-color_white)",
    black: "var(--cc-color_black)",
  },
  spacing: {
    0: "0px",
    1: "var(--cc-space_0)",
    2: "var(--cc-space_2)",
    3: "var(--cc-space_3)",
    4: "var(--cc-space_4)",
    5: "var(--cc-space_5)",
    6: "var(--cc-space_6)",
    7: "var(--cc-space_7)",
    8: "var(--cc-space_8)",
    9: "var(--cc-space_9)",
    12: "var(--cc-space_12)",
    16: "var(--cc-space_16)",
    20: "var(--cc-space_20)",
    24: "var(--cc-space_24)",
    32: "var(--cc-space_32)",
    40: "var(--cc-space_40)",
    48: "var(--cc-space_48)",
  },
  fontWeight: {
    bold: "var(--cc-typo_font-weight--bold)",
    medium: "var(--cc-typo_font-weight--medium)",
    regular: "var(--cc-typo_font-weight--regular)",
    light: "var(--cc-typo_font-weight--light)",
  },
  fontFamily: {
    sans: "var(--cc-typo_font-family--sans)",
  },
  fontSize: {
    "8xl": [
      "var(--cc-typo_font-size--8xl)",
      { lineHeight: "var(--cc-typo_line-height--8xl)" },
    ],
    "7xl": [
      "var(--cc-typo_font-size--7xl)",
      { lineHeight: "var(--cc-typo_line-height--7xl)" },
    ],
    "6xl": [
      "var(--cc-typo_font-size--6xl)",
      { lineHeight: "var(--cc-typo_line-height--6xl)" },
    ],
    "5xl": [
      "var(--cc-typo_font-size--5xl)",
      { lineHeight: "var(--cc-typo_line-height--5xl)" },
    ],
    "4xl": [
      "var(--cc-typo_font-size--4xl)",
      { lineHeight: "var(--cc-typo_line-height--4xl)" },
    ],
    "3xl": [
      "var(--cc-typo_font-size--3xl)",
      { lineHeight: "var(--cc-typo_line-height--3xl)" },
    ],
    "2xl": [
      "var(--cc-typo_font-size--2xl)",
      { lineHeight: "var(--cc-typo_line-height--2xl)" },
    ],
    xl: [
      "var(--cc-typo_font-size--xl)",
      { lineHeight: "var(--cc-typo_line-height--xl)" },
    ],
    lg: [
      "var(--cc-typo_font-size--lg)",
      { lineHeight: "var(--cc-typo_line-height--lg)" },
    ],
    base: [
      "var(--cc-typo_font-size--base)",
      { lineHeight: "var(--cc-typo_line-height--base)" },
    ],
    sm: [
      "var(--cc-typo_font-size--sm)",
      { lineHeight: "var(--cc-typo_line-height--sm)" },
    ],
    xs: [
      "var(--cc-typo_font-size--xs)",
      { lineHeight: "var(--cc-typo_line-height--xs)" },
    ],
  },
};
